### PR TITLE
Add "-k" flag

### LINKED ISSUE #362: SSL certificate problem: self-signed certificate in certificate chain
```
> [base 5/5] RUN wget -qO- https://aka.ms/install-artifacts-credprovider.sh | bash:
#0 2.912 INFO: Creating the nuget plugin directory (i.e. /root/.nuget/plugins).
#0 2.915 Downloading from https://github.com/Microsoft/artifacts-credprovider/releases/latest/download/Microsoft.NuGet.CredentialProvider.tar.gz
#0 3.129 curl: (60) SSL certificate problem: self-signed certificate in certificate chain
#0 3.129 More details here: https://curl.se/docs/sslcerts.html
#0 3.129
#0 3.129 curl failed to verify the legitimacy of the server and therefore could not
#0 3.129 establish a secure connection to it. To learn more about this situation and
#0 3.129 how to fix it, please visit the web page mentioned above.
#0 3.133 tar: invalid magic
#0 3.134 tar: short read
#0 3.134 tar: plugins/netcore: not found in archive
```

### PR DESCRIPTION
**Pull request by marco-carvalho**
closes #362

### CODE REVIEW

**Comment by trejjam** [comment]
This PR introduces a security threat to the project. The `-k` option stands for `--insecure`. Just fix your certificate chain on your local machine.

**Comment by trejjam** [comment]
Well, the `-k` create an issue for the entire world (at least the part using this provider :D ), not just your company.

**Comment by trejjam** [comment]
Btw the issue is not with your company's self-signed certificate. But with the missing root certificate of github.com. You may want to fix it with something like `update-ca-certificates` (depending on your distro).

**Review by JohnSchmeichel — COMMENTED** [review]
Not going to enable insecure flag. If this is the only mechanism to workaround your companies certificate issues then I would suggest forking this script and hosting your own version with the additional options until the certificate issues can be resolved.

**Pull request closed without merging**
